from typing import List

DEFAULT_ROLES_PATH: List[str]
DEPRECATION_WARNINGS: bool
YAML_FILENAME_EXTENSIONS: list[str]
_ACTION_ALL_INCLUDE_IMPORT_TASKS: tuple[str]
_ACTION_ALL_PROPER_INCLUDE_IMPORT_ROLES: tuple[str]
