DEFAULT_ROLES_PATH: list[str]
DEPRECATION_WARNINGS: bool
YAML_FILENAME_EXTENSIONS: list[str]
_ACTION_ALL_INCLUDE_IMPORT_TASKS: list[str]
_ACTION_INCLUDE_TASKS: list[str]
_ACTION_IMPORT_TASKS: list[str]
_ACTION_ALL_PROPER_INCLUDE_IMPORT_ROLES: list[str]
_ACTION_IMPORT_PLAYBOOK: list[str]
_ACTION_INCLUDE: list[str]
_ACTION_SET_FACT: list[str]
_ACTION_INCLUDE_VARS: list[str]

ANY_ERRORS_FATAL: bool
TASK_TIMEOUT: int
DEFAULT_POLL_INTERVAL: int
DEFAULT_STRATEGY: str
