from typing import Tuple
from collections import UserDict, UserList

import yaml

AnsiblePosition = Tuple[str, int, int]

class AnsibleBaseYAMLObject:
    ansible_pos: AnsiblePosition = ...

class AnsibleMapping(AnsibleBaseYAMLObject, dict[str, AnsibleBaseYAMLObject]): ...
class AnsibleUnicode(AnsibleBaseYAMLObject, str): ...
class AnsibleSequence(AnsibleBaseYAMLObject, list[AnsibleBaseYAMLObject]): ...
class AnsibleVaultEncryptedUnicode(yaml.YAMLObject, AnsibleBaseYAMLObject): ...
