from __future__ import annotations

class Templar:
    def __init__(self, loader: object) -> None: ...
    def do_template(self, data: str) -> str: ...
    def template(self, data: str) -> str: ...
    def is_template(self, data: object) -> bool: ...
