[tool.poetry]
name = "ansiblegraphextractor"
version = "0.1.0"
description = ""
authors = ["Ruben Opdebeeck <ropdebee@vub.be>"]

[tool.poetry.dependencies]
python = "^3.10"
networkx = "^2.5.1"
click = "^7.1.2"
pydantic = "^1.8.1"
cattrs = "^1.7.1"
pendulum = "^2.1.2"
graphviz = "^0.16"
loguru = "^0.5.3"
voyager = {path = "/Users/ruben/Documents/PhD/IaC/Voyager"}

[tool.poetry.group.dev.dependencies]
hypothesis = "^6.17.0"
types-PyYAML = "^5.4.11"
mypy = "^0.982"
MarkupSafe = "2.0.1"



[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
pytest-describe = "^1.0.0"
coverage = "^5.5"
pytest-cov = "^2.11.1"
pytest-sugar = "^0.9.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--cov=. --cov-report html"

[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "^\\s*if TYPE_CHECKING:",
    "@overload",
    "^\\s*\\.\\.\\.$",
    "raise NotImplementedError\\(",
    "raise TypeError\\(",
    "raise ValueError\\(",
    "raise RuntimeError\\(",
    "@pytest\\.mark\\.xfail",
    "@pytest\\.mark\\.integration",
    "@pytest\\.mark\\.smoke",
    "def __repr__\\(",
]

[tool.mypy]
follow_imports = "normal"

# disallow_any_expr = True
disallow_any_unimported = true
disallow_any_decorated = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_any_explicit = true

disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true

no_implicit_optional = true
strict_optional = true

warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
warn_return_any = true
# implicit_reexport = False
strict_equality = true

warn_redundant_casts = true
warn_unused_configs = true
