from __future__ import annotations

from ansible.playbook.base import FieldAttributeBase as FieldAttributeBase

class LoopControl(FieldAttributeBase):
    loop_var: str = ...
    index_var: str = ...
    label: str = ...
    pause: float = ...
    extended: bool = ...
    extended_allitems: bool = ...
    break_when: list[str] = ...
